### ISSUE TITLE
ReferenceError: expect is not defined

### ISSUE THREAD

**Issue by ivansabik** [TGOlson/dupertest#8]
Hi, I tried running examples from repo but getting:

```
  mockController
    Basic examples using expect
      1) should return an error if the entity does not exist
      2) should return an entity if one exists
    Basic examples using end
      3) should return an error if the entity does not exist
      4) should return an entity if one exists
    More complex example building up the request object
      5) should return an entity with the original request url
    Transforming the request before it is sent
      6) should allow the request to be dynamically modified


  0 passing (20ms)
  6 failing

  1) mockController Basic examples using expect should return an error if the entity does not exist:
     ReferenceError: expect is not defined
      at Object.assertion [as send] (/home/ivansabik/Desktop/dupertest/lib/request.js:54:5)
      at exports.show (entities-controller.js:15:9)
      at Request.end (/home/ivansabik/Desktop/dupertest/lib/request.js:76:3)
      at Request.expect (/home/ivansabik/Desktop/dupertest/lib/request.js:58:8)
      at Context.<anonymous> (entities-controller_spec.js:22:10)

  2) mockController Basic examples using expect should return an entity if one exists:
     ReferenceError: expect is not defined
      at Object.assertion [as send] (/home/ivansabik/Desktop/dupertest/lib/request.js:54:5)
      at exports.show (entities-controller.js:13:9)
      at Request.end (/home/ivansabik/Desktop/dupertest/lib/request.js:76:3)
      at Request.expect (/home/ivansabik/Desktop/dupertest/lib/request.js:58:8)
      at Context.<anonymous> (entities-controller_spec.js:28:10)

  3) mockController Basic examples using end should return an error if the entity does not exist:
     ReferenceError: expect is not defined
      at Object.send (entities-controller_spec.js:37:11)
      at exports.show (entities-controller.js:15:9)
      at Request.end (/home/ivansabik/Desktop/dupertest/lib/request.js:76:3)
      at Context.<anonymous> (entities-controller_spec.js:36:10)

  4) mockController Basic examples using end should return an entity if one exists:
     ReferenceError: expect is not defined
      at Object.send (entities-controller_spec.js:46:11)
      at exports.show (entities-controller.js:13:9)
      at Request.end (/home/ivansabik/Desktop/dupertest/lib/request.js:76:3)
      at Context.<anonymous> (entities-controller_spec.js:45:10)

  5) mockController More complex example building up the request object should return an entity with the original request url:
     ReferenceError: expect is not defined
      at Object.send (entities-controller_spec.js:71:11)
      at exports.somethingMoreComplex (entities-controller.js:31:7)
      at Request.end (/home/ivansabik/Desktop/dupertest/lib/request.js:76:3)
      at Context.<anonymous> (entities-controller_spec.js:70:10)

  6) mockController Transforming the request before it is sent should allow the request to be dynamically modified:
     ReferenceError: expect is not defined
      at Object.send (entities-controller_spec.js:91:11)
      at action (entities-controller_spec.js:81:13)
      at Request.end (/home/ivansabik/Desktop/dupertest/lib/request.js:76:3)
      at Context.<anonymous> (entities-controller_spec.js:90:10)
```
My command history looks thike this:
```
ich@meins ~/Desktop $ git clone https://github.com/TGOlson/dupertest.git
ich@meins ~/Desktop $ cd dupertest/
ich@meins ~/Desktop/dupertest $ npm install
jasmine-node@1.14.5 node_modules/jasmine-node
├── mkdirp@0.3.5
├── underscore@1.8.3
├── walkdir@0.0.10
├── coffee-script@1.10.0
├── requirejs@2.1.20
├── jasmine-reporters@1.0.2
├── jasmine-growl-reporter@0.0.3 (growl@1.7.0)
└── gaze@0.3.4 (minimatch@0.2.14, fileset@0.1.8)
ich@meins ~/Desktop/dupertest $ cd examples/
ich@meins ~/Desktop/dupertest/examples $ mocha entities-controller_spec.js 
```

**Comment by ivansabik** [comment]
My bad, was using mocha for running the test suite -_-

**Comment by TGOlson** [comment]
@ivansabik no worries, thanks for bringing that up. Like you noticed, right now `expect` is hardcoded to use a `jasmine` assertion method, but that maybe that isn't ideal.
